# This is a basic workflow to help you get started with Actions y

name: Publish GitHub Actions Artifacts

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step1 - Create a temp dir
        run: mkdir temp_dir

      - name: Step2 - Add artifacts to publish to the temp dir
        run: |
          cd temp_dir
          echo 'alpha'    > alpha.html
          echo 'abhishek' > abhishek.html
          echo 'verma'    > verma.html
          cd ..

      - name: Step3 - Use the uploda artifact github actions
        uses: actions/upload-artifact@v2
        with: 
            name: assets-of-temp-dir
            path: temp_dir