name: Trigger Reusable Workflow 

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Registry Release Version'
        required: true
      snapshot-version:
        description: 'Next snapshot version'
        required: true

jobs: 
    job1:
      name: first job
      runs-on: ubuntu-latest
      steps: 
        - name: step1
          uses: actions/checkout@v2
        - name: step2
          run: env
          
    job2: 
      name: secound job
      runs-on: windows-latest
      steps:
        - name: step1
          uses: actions/checkout@v2
        - name: step2
          run: "Get-ChildItem Env: | Sort-Object Name"
          
    notify-sdk:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
 
       - uses: dorny/paths-filter@v2
         id: changes
         with:
           base: master
           filters: |
             readme:
               - 'README.md'
       - name: Repository Dispatch
         uses: peter-evans/repository-dispatch@v1
         with:
           token: ${{ secrets.ACCESS_TOKEN }}
           repository: rishab-prasad/practice-github-actions
           event-type: on-oas-updated
           client-payload: '{"openapi_file_path": "app/src/main/resources-unfiltered/META-INF/resources/api-specifications/registry/v2/openapi.json"}'
 
